### ISSUE TITLE
?

### ISSUE THREAD

**Issue by tanto-mc** [Interlink-Media/Sierra#20]
Does it make sense to use Exploit Fixer or does your plugin cope without it?

**Comment by SquareCodeFX** [comment]
Sierra is fully capable of handling any server issues caused by crashers at the packet level on its own. Additionally, Sierra offers good compatibility with other plugins and anticheats. However, I cannot guarantee how Sierra will interact with other anti-crash solutions, as this may cause problems or other misbehavior. Furthermore, I am not familiar with the system you mentioned. I know what my system can do, but I do not know what Exploit Fixer has that you find lacking in Sierra.

Best regards,
