### ISSUE TITLE
Feature request - option for recipe request

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Interlink-Media/Sierra#28]
I want an option to edit how many ms delay for recipe request, when i click too fast on recipe, the inventory close.

**Comment by SquareCodeFX** [comment]
This project is officially unsupported since I have developed version 2.0 of Sierra. The source code is public, so you can edit it yourself

**Comment by SquareCodeFX** [comment]
Buyable in the interface

**Comment by TDMidkwhatisxd** [comment]
Dont tell me this plugin is becoming paid too ;-;, at least will this free version be maintained?

**Comment by SquareCodeFX** [comment]
What started as a small fun project has developed into one of the strongest anti-crash tools on the market. The time it takes to keep this project up to date with new checks and features has become too much for me to continue making it open source and free, especially since I manage this project on my own.

And no, the free version will no longer receive updates from me. It will remain a perfect anti-crash tool for version 1.8 and an adequate one for 1.9+. I will now put all my knowledge into the next generation of this system.ä
